// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nI0VqrDHSfGbnm_HFK-y9tyX8U9jVMA',
    appId: '1:9899547185:web:c0741a20ff81654aed1310',
    messagingSenderId: '9899547185',
    projectId: 'fir-flutter-ecaf4',
    authDomain: 'fir-flutter-ecaf4.firebaseapp.com',
    storageBucket: 'fir-flutter-ecaf4.firebasestorage.app',
    measurementId: 'G-GWLY7VVJX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRYdhqUAczF_NloHspQlFIiWabsZ0JUIE',
    appId: '1:9899547185:android:087f7a49d6fde5f3ed1310',
    messagingSenderId: '9899547185',
    projectId: 'fir-flutter-ecaf4',
    storageBucket: 'fir-flutter-ecaf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdYEVIf2TLIsfXJJ1kSvHZHxLHMOlFIZs',
    appId: '1:9899547185:ios:4d98f32299b78219ed1310',
    messagingSenderId: '9899547185',
    projectId: 'fir-flutter-ecaf4',
    storageBucket: 'fir-flutter-ecaf4.firebasestorage.app',
    iosBundleId: 'com.example.mxhFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdYEVIf2TLIsfXJJ1kSvHZHxLHMOlFIZs',
    appId: '1:9899547185:ios:4d98f32299b78219ed1310',
    messagingSenderId: '9899547185',
    projectId: 'fir-flutter-ecaf4',
    storageBucket: 'fir-flutter-ecaf4.firebasestorage.app',
    iosBundleId: 'com.example.mxhFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2nI0VqrDHSfGbnm_HFK-y9tyX8U9jVMA',
    appId: '1:9899547185:web:f81aae7442202887ed1310',
    messagingSenderId: '9899547185',
    projectId: 'fir-flutter-ecaf4',
    authDomain: 'fir-flutter-ecaf4.firebaseapp.com',
    storageBucket: 'fir-flutter-ecaf4.firebasestorage.app',
    measurementId: 'G-5H8D3CC9R5',
  );
}
